import Head from "next/head";

export default function Home() {
  return (
    <div className="flex items-center justify-center w-screen h-screen">
      <Head>
        <title>Air bnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Test</h2>
    </div>
  );
}
