import Head from "next/head";
import HomePage from "../components/Pages/HomePage";

export default function Home({ data, cardRes }) {
  return (
    <div className="pb-4">
      <Head>
        <title>Airbnb | Find your next adventure.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage places={data} cardData={cardRes} />
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch(`https://links.papareact.com/pyp`);
  const res = await exploreData.json();

  const cardsData = await fetch(`https://links.papareact.com/zp1`);
  const cardRes = await cardsData.json();

  return {
    props: {
      data: res,
      cardRes,
    },
  };
}
