import Head from "next/head";
import HomePage from "../components/Pages/HomePage";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>AirBnB | Find your next adventure.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Banner */}
      <HomePage places={data} />
      {/* Featured Locations */}
    </div>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch(`https://links.papareact.com/pyp`);
  const res = await exploreData.json();

  const test = "asda";
  return {
    props: {
      data: res,
    },
  };
}
